library(sf); library(spdep); library(spatialreg); library(dplyr); library(readr)
lga <- st_read('results/lga_lisa.gpkg', quiet=TRUE)
nb <- poly2nb(lga, queen=TRUE)
lw <- nb2listw(nb, style='W', zero.policy=TRUE)
lga$log_area <- log(lga$area_km2)
cat('N', nrow(lga), '\n')
print(summary(lga$density))
m0 <- lm(density ~ log_area, data=lga)
cat('OLS density ~ log_area\n')
print(summary(m0))
cat('AIC OLS', AIC(m0), '\n')
mlag <- lagsarlm(density ~ log_area, data=lga, listw=lw, zero.policy=TRUE, tol.solve=1e-10)
cat('LAG\n')
print(summary(mlag))
cat('lag AIC', AIC(mlag), ' rho', mlag$rho, '\n')
merr <- errorsarlm(density ~ log_area, data=lga, listw=lw, zero.policy=TRUE, tol.solve=1e-10)
cat('ERROR\n')
print(summary(merr))
cat('error AIC', AIC(merr), ' lambda', merr$lambda, '\n')
# climate on 34
nasa <- read_csv('data/processed/nasa_annual.csv', show_col_types=FALSE)
nasa$city <- tolower(nasa$city)
state_to_city <- c('Federal Capital Territory'='abuja','Lagos'='lagos','Kano'='kano','Rivers'='port_harcourt','Gombe'='gombe')
lga$city_key <- state_to_city[lga$NAME_1]
lga <- left_join(lga, nasa, by=c('city_key'='city'))
dat <- lga %>% filter(n>0, !is.na(prectot_sum))
cat('climate N', nrow(dat), '\n')
print(head(dat %>% st_drop_geometry() %>% select(NAME_2, NAME_1, density, log_area, prectot_sum, t2m_mean)))
if(nrow(dat)>=10){
  m0c <- lm(density ~ log_area + prectot_sum + t2m_mean, data=dat %>% st_drop_geometry())
  cat('OLS climate\n')
  print(summary(m0c))
  lga_sub <- lga %>% filter(n>0, !is.na(prectot_sum))
  nb_sub <- poly2nb(lga_sub, queen=TRUE)
  lw_sub <- nb2listw(nb_sub, style='W', zero.policy=TRUE)
  cat('nb_sub isolates', sum(card(nb_sub)==0), '\n')
  mlc <- lagsarlm(density ~ log_area + prectot_sum + t2m_mean, data=lga_sub, listw=lw_sub, zero.policy=TRUE)
  cat('LAG climate\n')
  print(summary(mlc))
  mec <- errorsarlm(density ~ log_area + prectot_sum + t2m_mean, data=lga_sub, listw=lw_sub, zero.policy=TRUE)
  cat('ERROR climate\n')
  print(summary(mec))
}
